version: '2'

services:
  rentals-app:
    image: 'rentals:latest'
    container_name: rentals-app
    depends_on:
      rentals-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rentals-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    ports:
      - 8083:8080
  rentals-db:
    image: 'postgres:16-alpine'
    container_name: rentals-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compose-postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
